//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int UserUserId { get; set; }
        public int ProductID { get; set; }
        public string Ammount { get; set; }
        public string UpdateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
