//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Stock = new HashSet<Stock>();
            this.OrderProducts = new HashSet<OrderProducts>();
            this.Discount = new HashSet<Discount>();
            this.Cart = new HashSet<Cart>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Price { get; set; }
        public short CategoryID { get; set; }
        public short ManufacturerID { get; set; }
        public string Picture { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
