//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.CartProducts = new HashSet<CartProducts>();
        }
    
        public string ID { get; set; }
        public string UserID { get; set; }
        public string UpdateDate { get; set; }
    
        public virtual ICollection<CartProducts> CartProducts { get; set; }
        public virtual User User { get; set; }
    }
}
