//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_MVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public long ID { get; set; }
        public string Cost { get; set; }
        public string Status { get; set; }
        public string SubmitTime { get; set; }
        public string ArrivalTime { get; set; }
        public string DoneTime { get; set; }
        public short LocationID { get; set; }
        public int UserId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual User User { get; set; }
    }
}
